language: go
go:
- 1.3.3
- 1.4.3
- 1.5.3
- 1.6
- tip
matrix:
  allow_failures:
  - go: tip
before_install:
- openssl aes-256-cbc -K $encrypted_b096a1fd8e8f_key -iv $encrypted_b096a1fd8e8f_iv
  -in client_secret.json.enc -out client_secret.json -d
